In [1]:
import numpy as np
import pickle
import random_idx
import string

N = 10000
k = 5000
ordered = 1
alph = string.lowercase + " "

fread = open("alice_RI_letters", "r")
RI_letters = pickle.load(fread)
fread.close()

lang_vec = [];
vocab_vec = [];

def create_lang_vocab(cluster_sizes, min_,max_,N=N, k=k):
    total_lang = np.zeros((1,N))
    # generate english vector
    for cz in cluster_sizes:
        print "generating language vector of cluster size", cz
        # which alphabet to use
        lang_vector,vocab_vector = random_idx.generate_vocab_lang_vectors(N, RI_letters, cz, ordered, "preprocessed_texts/AliceInWonderland.txt", min_,max_, alph)        
        total_lang += lang_vector
    return total_lang, vocab_vector



for i in range(4):
    print "developing lang_vec vocab_vec for "+str(i)
    x = create_lang_vocab([i], 40000, 10000);
    lang_vec.append(x[0])
    vocab_vec.append(x[1])


height has been deprecated.

2016-02-05 13:10
developing lang_vec vocab_vec for 0
generating language vector of cluster size 0
developing lang_vec vocab_vec for 1
generating language vector of cluster size 1
developing lang_vec vocab_vec for 2
generating language vector of cluster size 2
developing lang_vec vocab_vec for 3
generating language vector of cluster size 3


In [2]:
lang_vec

[array([[ 120433.,  120433.,  120433., ...,  120433.,  120433.,  120433.]]),
 array([[-61330., -39456.,  48166., ...,  10920.,  27382.,  23746.]]),
 array([[-12591.,  20939.,  -7377., ...,  -4165.,  10617.,    851.]]),
 array([[-1917.,  2919.,   283., ..., -1577., -4289.,  5987.]])]

In [3]:
def count_alice(pref):
    f = open("preprocessed_texts/AliceInWonderland.txt","r")
    text = f.read().strip()
    f.close()
    return text.count(pref)
    

In [4]:
temp = random_idx.id_vector(N, "yz", alph, RI_letters, ordered)
print(np.dot(temp, vocab_vec[2].T))
print(np.dot(temp, lang_vec[2].T))


print(count_alice("yz"))


temp = random_idx.id_vector(N, "po", alph, RI_letters, ordered)
print(np.dot(temp, vocab_vec[2].T))
print(np.dot(temp, lang_vec[2].T))


print(count_alice("po"))


[[-5980.]]
[[ 1101588.]]
0
[[-14212.]]
[[ 2325700.]]
224
